apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gitops-updater"
spec:
  selector:
    matchLabels:
      app: "gitops-updater"
  replicas: 1
  template:
    metadata:
      labels:
        app: "gitops-updater"
    spec:
      serviceAccountName: "gitops-updater"
      containers:
        - name: "gitops-updater"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - configMapRef:
                name: "gitops-updater-configuration"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/healthz/liveness
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/healthz/readiness
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
